#!/usr/bin/env bash
set -euo pipefail

site_dir="${1:-public}"
log_dir="${site_dir}/logs"

rm -rf "${site_dir}"
mkdir -p "${log_dir}"

build_status=0
test_status=0

set +e
cargo build >"${log_dir}/cargo-build.txt" 2>&1
build_status=$?
cargo test >"${log_dir}/cargo-test.txt" 2>&1
test_status=$?
set -e

python3 - "$site_dir" "$build_status" "$test_status" <<'PY'
import html
import pathlib
import sys

site_dir = pathlib.Path(sys.argv[1])
build_status = int(sys.argv[2])
test_status = int(sys.argv[3])

root = pathlib.Path.cwd()


def read_text(path):
    return (root / path).read_text(encoding="utf-8")


def log_block(path):
    text = (site_dir / path).read_text(encoding="utf-8")
    return html.escape(text)


def status_label(code):
    return "passed" if code == 0 else "failed"


def page(title, body):
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <style>
    :root {{
      color-scheme: light dark;
      --bg: #f7f4ef;
      --text: #1e2528;
      --muted: #5e6a70;
      --panel: #ffffff;
      --border: #cfd7d9;
      --accent: #176a73;
      --accent-soft: #d7ecef;
      --code: #11181b;
    }}
    @media (prefers-color-scheme: dark) {{
      :root {{
        --bg: #15191b;
        --text: #eff3f4;
        --muted: #acb8bd;
        --panel: #20272a;
        --border: #3f4b50;
        --accent: #72c7d0;
        --accent-soft: #243b40;
        --code: #f4f7f8;
      }}
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.55;
    }}
    header, main {{
      width: min(1040px, calc(100% - 32px));
      margin: 0 auto;
    }}
    header {{
      padding: 36px 0 20px;
      border-bottom: 1px solid var(--border);
    }}
    h1 {{ margin: 0 0 10px; font-size: clamp(2rem, 4vw, 3rem); line-height: 1.05; }}
    h2 {{ margin-top: 36px; border-bottom: 1px solid var(--border); padding-bottom: 6px; }}
    h3 {{ margin-top: 28px; }}
    a {{ color: var(--accent); }}
    nav {{ display: flex; flex-wrap: wrap; gap: 10px; margin-top: 18px; }}
    nav a, .badge {{
      display: inline-flex;
      align-items: center;
      min-height: 32px;
      padding: 4px 10px;
      border: 1px solid var(--border);
      border-radius: 6px;
      background: var(--panel);
      text-decoration: none;
      color: var(--text);
    }}
    .badge {{ background: var(--accent-soft); }}
    main {{ padding: 22px 0 44px; }}
    pre {{
      overflow-x: auto;
      padding: 16px;
      border: 1px solid var(--border);
      border-radius: 6px;
      background: var(--panel);
      color: var(--code);
    }}
    code {{ font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; }}
    table {{ border-collapse: collapse; width: 100%; overflow-wrap: anywhere; }}
    th, td {{ border: 1px solid var(--border); padding: 8px; vertical-align: top; }}
    th {{ background: var(--accent-soft); text-align: left; }}
    blockquote {{ border-left: 4px solid var(--accent); margin-left: 0; padding-left: 16px; color: var(--muted); }}
  </style>
</head>
<body>
  <header>
    <h1>Sequential Directory Tree</h1>
    <p>Published specification, tool information, and latest build/test output.</p>
    <nav>
      <a href="index.html">Overview</a>
      <a href="sdt-spec.html">Specification</a>
      <a href="tools.html">Tools</a>
      <a href="ci.html">Build &amp; Test</a>
    </nav>
  </header>
  <main>
{body}
  </main>
</body>
</html>
"""


def write_page(name, title, body):
    (site_dir / name).write_text(page(title, body), encoding="utf-8")


def markdown_to_html(markdown):
    try:
        import markdown as md
    except Exception:
        escaped = html.escape(markdown)
        return f"<pre><code>{escaped}</code></pre>"
    return md.markdown(markdown, extensions=["fenced_code", "tables", "toc"])


overview = f"""
    <h2>Project Documents</h2>
    <p>This site is generated by GitHub Actions from the repository source.</p>
    <p>
      <span class="badge">cargo build: {status_label(build_status)}</span>
      <span class="badge">cargo test: {status_label(test_status)}</span>
    </p>
    <ul>
      <li><a href="sdt-spec.html">SDT specification</a></li>
      <li><a href="tools.html">SDT tooling proposal</a></li>
      <li><a href="ci.html">Latest build and test logs</a></li>
    </ul>
"""
write_page("index.html", "Sequential Directory Tree", overview)

write_page(
    "sdt-spec.html",
    "SDT Specification",
    markdown_to_html(read_text("sdt-spec.md")),
)
write_page(
    "tools.html",
    "SDT Tooling",
    markdown_to_html(read_text("tools.md")),
)

ci_body = f"""
    <h2>Build &amp; Test</h2>
    <p>
      <span class="badge">cargo build: {status_label(build_status)} ({build_status})</span>
      <span class="badge">cargo test: {status_label(test_status)} ({test_status})</span>
    </p>
    <h3>cargo build</h3>
    <pre><code>{log_block("logs/cargo-build.txt")}</code></pre>
    <h3>cargo test</h3>
    <pre><code>{log_block("logs/cargo-test.txt")}</code></pre>
"""
write_page("ci.html", "Build and Test", ci_body)
PY

if (( build_status != 0 || test_status != 0 )); then
  exit 1
fi
